---
title: "Gelman Section 3.7 Example"
output: html_notebook
---

## Book Example - section 3.7: bioassay

```{r}
library(knitr)
library(lubridate) # working with dates
library(broom)
library(gridExtra)
library(tidyverse) # data manipulation and visualization - loads several packages

```


The experimental data:

```{r}
df1 <- data.frame(
  x = c(-0.86, -0.30, -0.05, 0.73),
  n = c(5, 5, 5, 5),
  y = c(0, 1, 3, 5)
)
kable(df1)

```

We now form the 50 x 50  sampling grid, by forming all 2500 parameter point pairs (uniform probability):

```{r}
A=seq(-4,8,length.out=50)
B=seq(-10,40,length.out=50)


cA=rep(A,each=length(B))
cB=rep(B,length(A))



```

Computng log liklihood:


```{r}
logl = function(df,a,b) {
  df['y']*(a+b*df['x'])-df['n']*log1p(exp(a+b*df['x']))
}
```


Calculate likelyhoods:

```{r}
p=apply(df1,1,logl,cA,cB) %>% rowSums() %>% exp()
```

Sample from grid with replace

```{r}
nsamp=1000
samp_indices=sample(length(p),size=nsamp,replace=T,prob=p/sum(p))

samp_A <- cA[samp_indices[1:nsamp]]
samp_B <- cB[samp_indices[1:nsamp]]

samp_A <- cA[samp_indices]
samp_B <- cB[samp_indices]


#samp_A <- samp_A + runif(nsamp, (A[1] - A[2])/2, (A[2] - A[1])/2)
#samp_B <- samp_B + runif(nsamp, (B[1] - B[2])/2, (B[2] - B[1])/2)

```

Sample LD

```{r}
bpi <- samp_B > 0
samp_ld50 <- -samp_A[bpi]/samp_B[bpi]
```


posterior density plot




```{r}
xl <- c(-2, 8)
yl <- c(-2, 40)
pos <- ggplot(data = data.frame(cA ,cB, p), aes(cA, cB)) +
  geom_raster(aes(fill = p, alpha = p), interpolate = T) +
  geom_contour(aes(z = p), colour = 'black', size = 0.2) +
  coord_cartesian(xlim = xl, ylim = yl) +
  labs(x = 'alpha', y = 'beta') +
  scale_fill_gradient(low = 'yellow', high = 'red', guide = F) +
  scale_alpha(range = c(0, 1), guide = F)
```


plot samples

```{r}
sam <- ggplot(data = data.frame(samp_A, samp_B)) +
  geom_point(aes(samp_A, samp_B), color = 'blue') +
  coord_cartesian(xlim = xl, ylim = yl) +
  labs(x = 'alpha', y = 'beta')
```

plot histograpms
```{r}
his <- ggplot() +
  geom_histogram(aes(samp_ld50), binwidth = 0.02,
                 fill = 'steelblue', color = 'black') +
  coord_cartesian(xlim = c(-0.5, 0.5)) +
  labs(x = 'LD50 = -alpha/beta')
```

combine

```{r}
grid.arrange(pos, sam, his, nrow=3)
```

